# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default  # Seu pool com o agente auto-hospedado

variables:
  buildConfiguration: 'Release'
  outputFolder: '$(Build.ArtifactStagingDirectory)/publicacao'

steps:

# Etapa opcional: conferir versão do .NET
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restaurar dependências
- task: DotNetCoreCLI@2
  displayName: 'Restaurar pacotes NuGet'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Build do projeto
- task: DotNetCoreCLI@2
  displayName: 'Build do projeto'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Publicação para pasta local
- task: DotNetCoreCLI@2
  displayName: 'Publicar aplicação'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(outputFolder)'
    zipAfterPublish: true

# Publicar como artefato do pipeline
- task: PublishBuildArtifacts@1
  displayName: 'Publicar artefato'
  inputs:
    PathtoPublish: '$(outputFolder)'
    ArtifactName: 'Poke-minimal-api'